# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Implementation of a Kalman filter
#' @param y Data matrix (T x n)
#' @param H Observation matrix
#' @param Q State covariance
#' @param R Observation covariance
#' @param F Transition matrix
#' @param x0 Initial state vector
#' @param P0 Initial state covariance
KalmanFilter <- function(y, H, Q, R, F, x0, P0) {
    .Call(`_DFM_KalmanFilter`, y, H, Q, R, F, x0, P0)
}

#' Runs a Kalman smoother
#' @param F transition matrix
#' @param H observation matrix
#' @param R Observation covariance
#' @param xfT State estimates
#' @param xpTm State predicted estimates
#' @param PfT_v Variance estimates
#' @param PpT_v Predicted variance estimates
#' @return List of smoothed estimates
KalmanSmoother <- function(F, H, R, xfT, xpT, PfT_v, PpT_v) {
    .Call(`_DFM_KalmanSmoother`, F, H, R, xfT, xpT, PfT_v, PpT_v)
}

