# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Estep <- function(X, A, C, Q, R, F_0, P_0) {
    .Call(`_DFM_Estep`, X, A, C, Q, R, F_0, P_0)
}

fKF <- function(X, A, C, Q, R, F_0, P_0, retLL = FALSE) {
    .Call(`_DFM_fKF`, X, A, C, Q, R, F_0, P_0, retLL)
}

fKS <- function(A, ZTf, ZTp, VTf_v, VTp_v, F_0SEXP, P_0SEXP) {
    .Call(`_DFM_fKS`, A, ZTf, ZTp, VTf_v, VTp_v, F_0SEXP, P_0SEXP)
}

fKFS <- function(X, A, C, Q, R, F_0, P_0, retLL = FALSE) {
    .Call(`_DFM_fKFS`, X, A, C, Q, R, F_0, P_0, retLL)
}

ainv <- function(x) {
    .Call(`_DFM_ainv`, x)
}

apinv <- function(x) {
    .Call(`_DFM_apinv`, x)
}

